import Head from 'next/head';
import { useEffect, useState } from 'react';
import style from '../styles/Home.module.css';

export default function Home() {
  const [currentTestimonial, setCurrentTestimonial] = useState(0);
  const testimonials = [
    {
      name: 'Sophia Johnson',
      role: 'Senior Student',
      photo: 'https://randomuser.me/api/portraits/women/11.jpg',
      text: 'BIS has been an incredible learning experience! The dedication of the teachers and the engaging curriculum have made my journey in J.S.S 3 truly enriching. I appreciate the supportive environment and the opportunities for personal growth.',
    },
    {
      name: 'Ethan Rodriguez',
      role: 'Junior Student',
      photo: 'https://randomuser.me/api/portraits/men/12.jpg',
      text: "I'm enjoying my time at BIS! The academic challenges and extracurricular activities in J.S.S 2 keep me motivated. The school's commitment to holistic development has made my learning journey both enjoyable and rewarding.",
    },
    {
      name: 'Isabella Smith',
      role: 'Junior Student',
      photo: 'https://randomuser.me/api/portraits/women/13.jpg',
      text: "BIS is my second home! The supportive community and diverse learning opportunities in J.S.S 2 have shaped me into a well-rounded individual. I'm grateful for the friendships and knowledge gained during my time here.",
    },
    {
      name: 'Liam Thompson',
      role: 'Fresher',
      photo: 'https://randomuser.me/api/portraits/men/14.jpg',
      text: "I'm loving the creative atmosphere at BIS! As a J.S.S 1 student, I've been inspired by the innovative teaching methods and the emphasis on self-expression. BIS is fostering my passion for learning and creativity.",
    },
    {
      name: 'Ava Clark',
      role: 'Fresher',
      photo: 'https://randomuser.me/api/portraits/women/15.jpg',
      text: "BIS offers a welcoming environment for newcomers like me! In J.S.S 1, I've found a diverse range of activities and a supportive community. The teachers' dedication to our success is truly commendable.",
    },
    {
      name: 'Noah Evans',
      role: 'Senior Student',
      photo: 'https://randomuser.me/api/portraits/men/16.jpg',
      text: "BIS's commitment to excellence is evident in every aspect! As a J.S.S 3 student, I appreciate the school's focus on academic rigor and character development. BIS is preparing me for a successful future.",
    },
    {
      name: 'Grade 6',
      role: 'Fashion Enthusiast',
      photo: 'https://randomuser.me/api/portraits/women/17.jpg',
      text: "BIS is not just a school; it's a community that fosters individuality! The school's environment has allowed me to explore my interests, including fashion. It's a fantastic place for students seeking a well-rounded education.",
    },
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTestimonial((prev) => (prev + 1) % testimonials.length);
    }, 10000);

    return () => clearInterval(interval);
  }, [testimonials.length]);
  return (
    <>
      <Head>
        <title>Bendonalds</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <div className={`${style.sections} ${style.sectionA}`}>
            <section className={style.sectionAInner}>
              <h1>Bendonalds International Secondary School</h1>
              <p className='lead'>A place to learn and grow</p>
            </section>
          </div>
          <section className={style.sectionB}>
            <h1>Courses We Offer</h1>
            <div className={style.sectionBInner}>
              <div className={style.curses}>
                <h4>Nursery</h4>
                <p>
                  Alphabet Adventures Number Carnival Creative Canvas Tiny Tech
                  Explorers Nature Detectives Rhythm & Rhyme
                </p>
              </div>
              <div className={style.curses}>
                <h4>Primary</h4>
                <p>Math, Language, Science, Arts, Digital, Social Studies.</p>
              </div>
              <div className={style.curses}>
                <h4>Secondary</h4>
                <p>
                  Advanced Math/Science, Language Mastery, In-depth Sciences,
                  Creative Arts, Digital Innovations, Global Perspectives.
                </p>
              </div>
            </div>
          </section>
          <section className={style.sectionD}>
            <div className={style.imgD}></div>
            <div className={style.sectionDInner}>
              <h1>Why Our School Is The Best</h1>
              <p>
                Welcome to Bendonalds International Secondary School, where
                education transcends boundaries! Renowned for academic
                brilliance, our school embraces cutting-edge facilities,
                holistic development, and a global perspective. With innovative
                teaching methods, a supportive community, and a celebration of
                diversity, BendoNation is not just a school; it's a vibrant
                ecosystem nurturing tomorrow's leaders. Join us on an
                unparalleled educational journey where excellence knows no
                bounds!
              </p>
            </div>
          </section>
          <section className={style.sectionC}>
            <h1>Our Facilities</h1>
            <div className={style.sectionCInner}>
              <div className={style.campus}>
                <div className={style.imgA}></div>
              </div>
              <div className={style.campus}>
                <div className={style.imgB}></div>
              </div>
              <div className={style.campus}>
                <div className={style.imgC}></div>
              </div>
            </div>
          </section>
          <section className={style.sectionE}>
            <section className={style.testimonialSection}>
              <h1>What Our Students Say</h1>
              <div className={style.testimonialContainer}>
                <div className={style.progressBar}></div>
                <div className={style.quote}></div>
                <p id='testimonial' className={style.testimonial}>
                  {testimonials[currentTestimonial].text}
                </p>
                <div className={style.user}>
                  <img
                    id='photo'
                    className={style.userImage}
                    src={testimonials[currentTestimonial].photo}
                    alt=''
                  />
                  <div className={style.userDetails}>
                    <h4 id='name' className={style.name}>
                      {testimonials[currentTestimonial].name}
                    </h4>
                    <p id='role' className={style.role}>
                      {testimonials[currentTestimonial].role}
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </section>
        </div>
      </main>
    </>
  );
}
