import Head from "next/head";
import Image from "next/image";
import style from "../styles/Home.module.css";
import SchoolHighlights from "@/components/schoolHighlights";
import NewsSection from "@/components/NewsSection";
import Newsletter from "@/components/NewLetter";
// import schoolBackground from "../assets/school-background.jpg";
import schoolBackgroundimg from "../assets/img-background.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Super School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <section className={style.heroSection}>
            <Image
              src={schoolBackgroundimg}
              className={style.background_image}
              loading="lazy"
            />

            <div className={style.heroContent}>
              <h2 className={style.hero_heading}>Discover Your Potential</h2>
              <p className={style.hero_text}>
                Unlock the doors to knowledge and endless possibilities.
              </p>

              <div className={style.explore}>
                <a href="#programs">Explore Programs</a>
              </div>
            </div>
          </section>
          <SchoolHighlights />
          <NewsSection />
          <Newsletter />
        </div>

        <footer className=" bg-dark text-light text-center mt-4 py-3">
          <p>
            &copy; {new Date().getFullYear()} Our School. All rights reserved.
          </p>
        </footer>
      </main>
    </>
  );
}
