import Head from 'next/head'
import style from '../styles/Home.module.css'
import SchoolHighlights from '@/components/schoolHighlights';
import NewsSection from '@/components/NewsSection';



export default function Home() {
  return (
    <>
      <Head>
        <title>Super School</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='container'>
          <header className='text-center mt-5'>
            <h1>Welcome to Super School</h1>
            <p className='lead'>A place to learn and grow</p>
          </header>

          <section className={style.heroSection}>
            <div className={style.heroContent}>
              <h2 className='display-4'>Discover Your Potential</h2>
              <p className='lead '>
                Unlock the doors to knowledge and endless possibilities.
              </p>
              <a href='#programs' className='btn btn-secondary btn-lg'>
                Explore Programs
              </a>
            </div>
          </section>

          <SchoolHighlights/>
          <NewsSection/>

          <section className='my-5'>
            <div className='row'>
              <div className='col-md-6'>
                <h2>About Us</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum sed feugiat lectus. Sed in risus vel mi tincidunt
                  cursus eu vel massa.
                </p>
              </div>
              <div className='col-md-6'>
                <h2>Our Programs</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum sed feugiat lectus. Sed in risus vel mi tincidunt
                  cursus eu vel massa.
                </p>
              </div>
            </div>
          </section>

          <section className='my-5'>
            <div className='row'>
              <div className='col-md-6'>
                <h2>Admissions</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum sed feugiat lectus. Sed in risus vel mi tincidunt
                  cursus eu vel massa.
                </p>
              </div>
              <div className='col-md-6'>
                <h2>Contact Us</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum sed feugiat lectus. Sed in risus vel mi tincidunt
                  cursus eu vel massa.
                </p>
              </div>
            </div>
          </section>

          <footer className='text-center py-3'>
            <p>
              &copy; {new Date().getFullYear()} Our School. All rights reserved.
            </p>
          </footer>
        </div>
      </main>
    </>
  );
}
