import Head from 'next/head';
import style from '../styles/Home.module.css';
import SchoolHighlights from '@/components/schoolHighlights';
import NewsSection from '@/components/NewsSection';
import Newsletter from '@/components/NewLetter';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bendonalds</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <div className={`${style.sections} ${style.sectionA}`}>
            <div className={style.overlay}></div>
            <section className={style.sectionAInner}>
              <h1>Bendonalds International Secondary School</h1>
              <p className='lead'>A place to learn and grow</p>
            </section>
          </div>
          <section className={style.sectionB}>
            <h1>Why Choose Our School</h1>
            <div className={style.sectionBInner}>
              <div className={style.curses}>
                <h4>Nursary</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Id,
                  necessitatibus soluta! Dolorem, repellat tempore. Nemo
                  voluptatibus enim veritatis alias non?
                </p>
              </div>
              <div className={style.curses}>
                <h4>Reception</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Id,
                  necessitatibus soluta! Dolorem, repellat tempore. Nemo
                  voluptatibus enim veritatis alias non?
                </p>
              </div>
              <div className={style.curses}>
                <h4>Secondary</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Id,
                  necessitatibus soluta! Dolorem, repellat tempore. Nemo
                  voluptatibus enim veritatis alias non?
                </p>
              </div>
            </div>
          </section>
          <section className={style.sectionD}>
            <div className={style.imgD}></div>
            <div className={style.sectionDInner}>
              <h1>Why Our School Is The Best</h1>
              <p>
                Welcome to Bendonalds International Secondary School, where
                education transcends boundaries! Renowned for academic
                brilliance, our school embraces cutting-edge facilities,
                holistic development, and a global perspective. With innovative
                teaching methods, a supportive community, and a celebration of
                diversity, BendoNation is not just a school; it's a vibrant
                ecosystem nurturing tomorrow's leaders. Join us on an
                unparalleled educational journey where excellence knows no
                bounds!
              </p>
            </div>
          </section>
          <section className={style.sectionC}>
            <h1>Our Facilities</h1>
            <div className={style.sectionCInner}>
              <div className={style.campus}>
                <div className={style.imgA}></div>
              </div>
              <div className={style.campus}>
                <div className={style.imgB}></div>
              </div>
              <div className={style.campus}>
                <div className={style.imgC}></div>
              </div>
            </div>
          </section>

          <SchoolHighlights />
          <NewsSection />
          <Newsletter />
        </div>

        <footer className=' bg-dark text-light text-center mt-4 py-3'>
          <p>
            &copy; {new Date().getFullYear()} Our School. All rights reserved.
          </p>
        </footer>
      </main>
    </>
  );
}
